data:
  dirs:
    main: "data"
    raw: "data/raw"
    intermediate: "data/intermediate"
  files:
    raw:
      features_train: "dengue_features_train.csv" 
      features_test: "dengue_features_test.csv"
      labels_train: "dengue_labels_train.csv"
    intermediate:
      features_clean: "dengue_features_clean.parquet"
      labels_clean: "dengue_labels_clean.parquet"
      nan_mask: "dengue_nan_mask.parquet"
preprocess:
  feature_groups:
    env_prefixes: ["ndvi_", "reanalysis_", "station_", "precipitation"]
    city: "city"
    datetime: "week_start_date"
    week: "weekofyear"
    target: "total_cases"
  outlier_perc:
    lower: 0.01
    upper: 0.99
  nan_threshold: 0.5
  missingness_features:
    group_prefixes: [["station", "precipitation"], "ndvi_s", "ndvi_n"]
    aggregated_feat_n: "pct_env_feat"
    new_feature_prefix: "missing_"
  combine_features:
    input_groups: 
      - ["ndvi_ne", "ndvi_nw"]
      - ["ndvi_se","ndvi_sw"]
    output_names: ["ndvi_north","ndvi_south"]
    aggregation: "mean"
  low_value_streak_features:
    target_streak_len_threshold: 26
    target_streak_feat_n: "low_case_streak"
    initial_streaks: True
    low_value_range: 2
  multicolinear:
    removal_list:
      - "reanalysis_sat_precip_amt_mm"
      - "reanalysis_dew_point_temp_k"
      - "reanalysis_air_temp_k"
      - "reanalysis_specific_humidity_g_per_kg"
      - "reanalysis_avg_temp_k"
      - "reanalysis_max_air_temp_k"
      - "reanalysis_min_air_temp_k"
# populate model section with real values or adjust ./src/config.py -> ModelConfig, otherwise Pydantic is complaining
model:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10


