data:
  dirs:
    main: "data"
    raw: "data/raw"
  files:
    raw:
      features_train: "dengue_features_train.csv" 
      features_test: "dengue_features_test.csv"
      labels_train: "dengue_labels_train.csv"
preprocess:
  feature_groups:
     env_prefixes: ["ndvi_", "reanalysis_", "station_", "precip"]
     temporal: ["year", "weekofyear", "week_start_date"]
     city: "city"
     week: "weekofyear"
     target: "total_cases"
  outlier_perc:
    lower: 0.01
    upper: 0.99
  nan_threshold: 0.5
# populate model section with real values or adjust ./src/config.py -> ModelConfig, otherwise Pydantic is complaining
model:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10


